In [34]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [35]:
train = pd.read_csv('./Dataset/apacheJIT/apachejit_train.csv')

train.head()

,commit_id,project,buggy,fix,year,author_date,la,ld,nf,nd,ns,ent,ndev,age,nuc,aexp,arexp,asexp
0,06a456ec1670fb26a86f8a18f5b55017ac961f39,apache/groovy,True,False,2003,1064916954,223,33,7,5,2,2.213687,0.142857,1.857143,12.142857,104,104.0,0.000606
1,79f50a10e7688279664146bb3c18837dada370a4,apache/groovy,False,False,2003,1071086882,138,10,9,3,1,1.692477,0.333333,32.333333,11.777778,287,287.0,228.000000
2,42437917f185f8efa3d947fae3bb08b584504650,apache/groovy,False,False,2003,1072801387,69,20,2,2,1,0.599911,1.500000,9.500000,16.500000,366,366.0,281.000000
3,b6616e5fb6d537229d307cf8647ef483468175a6,apache/groovy,True,False,2003,1072694298,52,2,2,2,1,0.380947,1.000000,6.000000,14.000000,364,364.0,279.000000
4,5d0abaebf0bd4b5d98f9ef173f23b3be5e6fb37f,apache/groovy,True,False,2003,1070542250,256,348,8,4,1,0.489213,0.375000,13.625000,20.000000,253,253.0,199.000000

# Pre Processing

In [36]:
X_train= train.drop(['commit_id','project','fix','year','author_date',"fix"],axis=1)
y_train= train['buggy']
X_train

,buggy,la,ld,nf,nd,ns,ent,ndev,age,nuc,aexp,arexp,asexp
0,True,223,33,7,5,2,2.213687,0.142857,1.857143,12.142857,104,104.000000,0.000606
1,False,138,10,9,3,1,1.692477,0.333333,32.333333,11.777778,287,287.000000,228.000000
2,False,69,20,2,2,1,0.599911,1.500000,9.500000,16.500000,366,366.000000,281.000000
3,True,52,2,2,2,1,0.380947,1.000000,6.000000,14.000000,364,364.000000,279.000000
4,True,256,348,8,4,1,0.489213,0.375000,13.625000,20.000000,253,253.000000,199.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
44829,False,1,0,1,1,1,0.000000,5.000000,1.000000,12.000000,1,1.000000,0.000000
44830,False,14,0,2,1,1,1.000000,1.500000,92.500000,2.000000,2,2.000000,0.000000
44831,False,50,0,2,2,1,0.855451,2.000000,3.500000,8.000000,3,3.000000,1.000000
44832,False,4,0,3,1,1,1.500000,3.000000,15.666667,19.000000,4,4.000000,0.000000
44833,False,8,29,9,3,1,2.533868,0.333333,100.000000,0.777778,10388,4081.682143,5238.000000

In [37]:
y_train

0         True
1        False
2        False
3         True
4         True
         ...
44829    False
44830    False
44831    False
44832    False
44833    False
Name: buggy, Length: 44834, dtype: bool

# Model Training

In [38]:
from sklearn.linear_model import LogisticRegression

# create the model
model = LogisticRegression()

# train the model
model.fit(X_train, y_train)

/Users/rebuy/Desktop/FCAI/GP/MyCode/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

# Testing

In [39]:
test = pd.read_csv('./Dataset/apacheJIT/aapachejit_test_large.csv')
test

,commit_id,project,buggy,fix,year,author_date,la,ld,nf,nd,ns,ent,ndev,age,nuc,aexp,arexp,asexp
0,999baceff36165d950a61dd9cc4342f252e64837,apache/flink,True,False,2017,1488367395,1439,87,80,4,1,5.746825,0.312500,50.625000,4.237500,223,178.833333,21.000000
1,2c799fb70aa47f9109714dc410862af24b4a0321,apache/hbase,False,False,2017,1486008708,983,4378,16,8,4,0.727304,5.250000,0.000000,64.750000,105,60.833333,0.109456
2,22ac8c00db676ccc01d1a44ec206ee17790b46b0,apache/camel,False,False,2017,1511424716,8,16,4,4,2,1.614005,3.500000,7.000000,18.000000,13353,4421.309524,0.992185
3,a9d3412b4ce40f5ab5a18756ede7e0606b653171,apache/hadoop,False,False,2017,1498508667,3,2,1,1,1,0.000000,15.000000,19.000000,25.000000,44,20.750000,15.000000
4,6cf958c2fa7dab4a028039c7c6e8f23456a5d7e5,apache/groovy,False,False,2017,1505541139,9,9,6,4,1,2.419382,5.000000,335.166667,118.000000,364,258.166667,244.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7521,f89ffc3ae18d2ff25fe7250c63ee850372b35094,apache/camel,False,False,2019,1548057494,18,15,11,4,1,3.359253,2.181818,67.363636,42.000000,4767,2909.000000,1681.000000
7522,bc0cb5bb0571e0044c5958142c519e9d2b7b610f,apache/camel,False,False,2019,1554966471,2,2,1,1,1,0.000000,2.000000,0.000000,3.000000,5747,3610.583333,2275.000000
7523,ee002068b75f5acaf909d7d82a6d212a879cdeb1,apache/camel,False,False,2019,1565342979,2,1,1,1,1,0.000000,4.000000,115.000000,5.000000,73,36.916667,7.000000
7524,c3c48f30f7450c3a04950805bba7fb1536db7c9d,apache/hbase,False,False,2019,1555858691,73,17,9,2,4,2.791749,6.666667,68.111111,36.777778,516,312.850000,0.145894
7525,36b52fc525876c17f55faff87bed66e91c3cc1e2,apache/camel,False,False,2019,1569053508,0,1,1,1,1,0.000000,20.000000,0.000000,67.000000,15351,4099.212951,7591.000000

In [40]:
X_test= test.drop(['commit_id','project','fix','year','author_date',"fix"],axis=1)
y_test= test['buggy']

In [41]:
model.score(X_test, y_test)

0.8227478076003188

# Saving the Model

In [42]:
import pickle

# save the trained model
with open("risk_logistic_model.pkl", "wb") as f:
    pickle.dump(model, f)

In [43]:
import pickle

with open("risk_logistic_model.pkl", "rb") as f:
    loaded_model = pickle.load(f)

In [44]:
predictions = loaded_model.predict(X_test)